# Generated by Django 4.1.3 on 2022-11-12 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='contact',
        ),
    ]
